name: data-module-template
channels:
  - conda-forge
  - bioconda
dependencies:
  - cffconvert >= 2.0.0
  - copier >= 9.4.1
  - graphviz >= 12.2.1
  - mkdocs-material >= 9.6.4
  - mypy >= 1.15.0
  - pip >= 25.0.1
  - pytest >= 8.3.4
  - python >= 3.12.9
  - ruff >= 0.9.6
  - snakefmt >= 0.10.2
  - snakemake-minimal >= 8.28.0
  - pip:
    - mkdocs-mermaid2-plugin >= 1.1.0
    - mkdocs-git-committers-plugin-2 >= 2.5.0
    - "git+https://github.com/calliope-project/clio.git@feature-clio-lib"
