name: CI

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v1
        with:
          # Any version from https://github.com/mamba-org/micromamba-releases
          micromamba-version: '1.5.6-0'
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@v0.8.3
      - name: Run tests
        run: pixi run test
