name: Release

on:
  release:
    types: [released]

jobs:
  add-latest-tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Run latest-tag
        uses: EndBug/latest-tag@v1.6.2
        with:
          # Name of the tag.
          ref: latest
