name: Reusable Pull Request CI tests for modules

on:
  workflow_call:

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4
      - name: setup-pixi
        uses: prefix-dev/setup-pixi@v0.8.3
      - name: Run tests
        run: pixi run test-integration
      - name: Run linting
        run: pixi run snakemake --lint
      - name: Archive integration test artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-logs-${{ matrix.os }}
          path: tests/integration/results/integration_test/logs
          retention-days: 30
