# Adapted from https://github.com/arup-group/actions-city-modelling-lab/blob/main/.github/workflows/template-check.yml
# MIT licensed

name: Reusable workflow for keeping up-to-date with template changes.
on:
  workflow_call:

defaults:
  run:
    shell: bash -l {0}

jobs:
  copier-issue:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
    env:
      UPDATE: false
    steps:
      - uses: actions/checkout@v4

      - name: Add dummy GitHub credentials
        run: |
          git config --global user.name Copier update
          git config --global user.email check@dummy.bot.com

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.8.8
        with:
          cache: true
          pixi-bin-path: ${{ runner.temp }}/bin/pixi
          pixi-version: v0.44.0
          run-install: true
          post-cleanup: true

      # Stash hides modifications to pixi.lock / pixi.toml caused by adding copier
      - name: Setup copier
        run: |
          pixi add copier
          git stash
          git stash clear

      - name: Run copier update
        run: pixi run copier update --skip-answered --defaults

      - name: Wait a bit for copier cleanups
        run: sleep 10s

      - name: Display differences
        run: git status --porcelain

      - name: Set update flag if changes occured
        run: test -z "$(git status --porcelain)" || echo "UPDATE=true" >> $GITHUB_ENV

      - name: Show environment variables
        run: |
          echo "$UPDATE"

      - name: Open issue
        if: env.UPDATE == true
        run: |
          gh issue --repo ${{ github.repository }} \
          create --title "Template update" \
          --body "A new version of the template has been published. Please update this project using \`copier update --skip-answered --defaults\` and review changes. If you need help, refer to the \`clio\` documentation or reach out to the calliope project team."
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
